### PR TITLE
Additional updates to AASHTO-2009 documenation

### PR DESCRIPTION
**Pull request by nluco-usgs**
The example request and response still need to be updated, when the service is finalized.

### CODE REVIEW

**Comment by nluco-usgs** [comment]
@emartinez-usgs, how does one vertically (instead of horizontally) list the site class options A-E in ...

    <dt id="siteClass">siteClass</dt>
    <dd>
      Site Class, as defined in Table 3.4.2.1-1 of seismic design reference document
      <br/>Options: <code>A</code> for "Hard rock", <code>B</code> for "Rock", <code>C</code> for "Very dense soil and soft rock", <code>D</code> for "Stiff soil", <code>E</code> (See Table 3.4.2.1-1)
    </dd>

**Comment by nluco-usgs** [comment]
Sorry, mistakenly closed the pull request.

**Comment by emartinez-usgs** [comment]
Most simply you could add a `<br/>` tag:
```html
<dt id="siteClass">siteClass</dt>
<dd>
  Site Class, as defined in Table 3.4.2.1-1 of seismic design reference document<br/>
  Options:<br/>
  <code>A</code> for "Hard rock",<br/>
  <code>B</code> for "Rock",<br/>
  <code>C</code> for "Very dense soil and soft rock",<br/>
  <code>D</code> for "Stiff soil",<br/>
  <code>E</code> (See Table 3.4.2.1-1)
</dd>
```

Better, you could use an `<ul>` with nested `<li>`, but I will not complain with either approach so long as HTML remains valid.

**Comment by nluco-usgs** [comment]
Thanks @emartinez-usgs , I've added the <\br> tags.

**Pull request merged**
